config/routes.rb
Rails.application.routes.draw do

  resources :consultations
  resources :doctors
  get 'doctors/new'
  get 'doctors/index'

  resources :patients

  devise_for :users , controllers: { registrations: "registrations" }

  authenticated :user do
    root to: 'home#dashboard' , as: :authenticated_root
  end
  

    root 'home#land'

end

app/models/consultation.rb
class Consultation < ActiveRecord::Base
  belongs_to :patient
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :consultations
  has_many :patients , through: :consultations
  belongs_to :user


  
end

app/models/role.rb
class Role < ActiveRecord::Base
  module RoleName
    PATIENT  = {code: 1, name: "Patient"}
    DOCTOR   = {code: 2, name: "Doctor"}
    HOSPITAL = {code: 3, name: "Hospital"}

    def self.all
      [PATIENT, DOCTOR, HOSPITAL]
    end

    def self.all_codes
      self.all.collect{|role_data| role_data[:code]}
    end
  end

  has_many :users

  def patient?
    self.code == RoleName::PATIENT[:code]
  end

  def doctor?
    self.code == RoleName::DOCTOR[:code]
  end

  def hospital?
    self.code == RoleName::HOSPITAL[:code]
  end

  def name
    RoleName.all
      .select{|role_data| role_data[:code] == self.code}
      .first[:name]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user_profile
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_devise_permitted_parameters, if: :devise_controller?

protected

  def configure_devise_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :role_id
  end
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  def new
    @consultation = Consultation.new
  end

  def create
    @consultation = Consultation.new(consultation_params)
    if @consultation.save
      redirect_to consultations_path
    else
      render "new"
    end
  end

  def index
    
  end

  private

  def consultation_params
    params.require(:consultation).permit(:appointment_date, :problem)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = current_user.build_doctor(doctor_params)
    if @doctor.save
      current_user.update_attribute(:profile_incomplete, false)
      redirect_to doctors_path
    else
      redirect_to new_doctor_path
    end
  end

  def index
    # if current_user.profile_incomplete?
    #   redirect_to edit_doctor_path(:id)
    # else
    #   redirect_to doctor_path(:id)
    # end
    @doctor = Doctor.all 
  end

  def show
    @doctor = current_user.doctor
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    @doctor = Doctor.find(params[:id])
    if @doctor.update_attribute(doctor_params)
      redirect_to doctor_path(id: current_user.id)
    else
      redirect_to edit_doctor_path
    end  
  end

  private

  def doctor_params
    params.require(:doctor).permit(:name, :gender, :qualification, :bio)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def land
    # if current_user
    #   redirect_to patients_path
    # end
  end

  def dashboard
    if current_user.patient?
      redirect_to new_patient_path
    elsif current_user.doctor? 
      redirect_to new_doctor_path
    else
      redirect_to root_path
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController


  def new
    @patient = Patient.new
  end


  def create
    save_patient("new")
  end

  def index 
    if current_user.profile_incomplete?
      redirect_to patient_path(:id)
    else
      redirect_to patient_path(current_user.patient)
    end
  end

  def show
    @patient = current_user.patient   
  end

  def edit
     @patient = Patient.find(params[:id])
  end

  def update
    save_patient("edit")
  end

private
  def save_patient(success_path)
    @patient = current_user.build_patient(patient_params)
    if @patient.save
      current_user.update_attribute(:profile_incomplete, false)
      redirect_to patient_path(id: current_user.id) 
    else
        render success_path
    end
  end

  def patient_params
    params.require(:patient).permit(:name, :age, :gender, :address, :city, :bloodgroup)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

   def after_sign_up_path_for(resource)
    return new_user_profile_path(id: current_user.id)
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  def new
    @profile = UserProfile.new
  end

  def create
    @profile = UserProfile.new(profile_params)
    if @profile.save
      redirect_to user_profiles_path
    else
      render 'new'
    end
  end

  def index
    if current_user.profile_incomplete?
      @profiles = UserProfile.find_or_create_by(user_id: current_user.id)
      redirect_to edit_user_profile_path(id: current_user.id)
    else
      redirect_to user_profiles_path
    end
  end

  def show

  end

  def edit
  end

  private
  def profile_params
       params.require(:user_profile).permit(:name , :age , :address ,  :gender , :bloodgroop , :city )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/consultations/index.html.erb
<h1>See your consultations Here</h1>

<%= @doctor%>
<%= link_to "New Appointment", new_consultation_path%>

app/views/consultations/new.html.erb
<p>
  hello
</p>
<%= simple_form_for @consultation do |f|%>
  <%= f.input :appointment_date %>
  <%= f.input :problem %>

  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/doctors/appointment.html.erb
<div class="row">
  <div class="container">
    <div class="col-sm-4">
      <i class="glyphicon glyphicon-user"></i>
    </div>
    <div class="col-sm-8">
      Patient_id: <br>
      Blood Pressure: <br>
      Test Result: <br>
    </div>
  </div>
</div>

app/views/doctors/edit.html.erb
<h2>Profile</h2>


<%= simple_form_for @doctor do |f| %>

  <%= f.error_notification %>

    <%= f.input :name, required: true %>
    <%= f.input :gender %>
    <%= f.input :qualification %>
    <%= f.input :bio %>

    <%= f.button :submit, "Update", class: "btn btn-primary btn-block" %>
  <h3>Cancel my account</h3>

  <p>Unhappy? <%= link_to "Cancel my account", data: { confirm: "Are you sure?" }, method: :delete %></p>

  <%= link_to "Back", :back %>
<% end %>

app/views/doctors/index.html.erb
index.html

app/views/doctors/new.html.erb
<h2>Profile</h2>


<%= simple_form_for @doctor do |f| %>

  <%= f.error_notification %>

    <%= f.input :name, required: true %>
    <%= f.input :gender %>
    <%= f.input :qualification %>
    <%= f.input :bio %>

    <%= f.button :submit, "Update", class: "btn btn-primary btn-block" %>
  <h3>Cancel my account</h3>

  <p>Unhappy? <%= link_to "Cancel my account", data: { confirm: "Are you sure?" }, method: :delete %></p>

  <%= link_to "Back", :back %>
<% end %>

app/views/doctors/show.html.erb
<h1>Details of Doctors</h1>

<li><%= @doctor.name %></li>
<li><%= @doctor.gender %></li>
<li><%= @doctor.qualification %></li>

<%= link_to "Edit", edit_doctor_path %>

app/views/header/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href="/">Med-Rec</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in?%>
        <li><%= link_to "Edit Profile", edit_user_profile_path(id: current_user.id) %></li>
        <li><a href="#"></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Signup", new_user_registration_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/land.html.erb
<h1>Welcome to our App</h1>
<p>We are here to take care of your health and records</p>

<% if current_user %>
<div class="row">
  <div class="col-md-6 well" >
   <h1>Consultations past</h1>
   <br>
   <p>Dr. Venkat Raman on 20-12-15</p>
   <p>Blood test at vijaya diagnos on 18-12-15</p>
  </div>
  <div class="col-md-6">
    <h1>Upcoming consultations</h1>
    <button>Book an appointment</button>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medrec</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'header/header' %>
<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/patients/_register.html.erb
<div class="tab-pane" role="tabpanel" id="step2">
  <fieldset class="well">
    <legend>Profile Details</legend>
    <div class="form-group">
      <div class="col-lg-10">
        <%= f.input :name, required: true, placeholder: "name", input_html: { class: "form-control control-label"} %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10">
        <%= f.input :address, 
        required: true, input_html: { class: "form-control control-label"} %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10">
        <%= f.input :age, required: true, input_html: { class: "form-control control-label"} %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10">
        <%= f.input :city, required: true, input_html: { class: "form-control control-label"} %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10">
      <%= f.input :bloodgroup, required: true, placeholder: "Blood-Group", input_html: { class: "form-control control-label"} %>
        <select class="form-control" id="select">
          <option>A+</option>
          <option>AB+</option>
          <option>O+</option>
          <option>A-</option>
          <option>AB-</option>
        </select>
        <br> 
      </div>
    </div>
     <ul class="list-inline pull-right">
      <li><button type="button" class="btn btn-primary next-step" >Save and continue</button></li>
    </ul>
  </fieldset>
</div>

app/views/patients/edit.html.erb
<h1>Edit</h1>
<%= simple_form_for @patient do|f|%>
  <%= f.input :name%>
  <%=f.input :age%>
  <%=f.input :bloodgroup%>
  <%=f.input :address%>
  <%=f.input :city%>
  <%= f.submit%>
<% end %>

app/views/patients/show.html.erb
<h1>
  Details of a user
</h1>

<li><%= @patient.name %></li>
<li><%= @patient.age%></li>
<li><%= @patient.gender%></li>
<li><%= @patient.bloodgroup%></li>
<li><%= @patient.address%></li>
<li><%= @patient.city%></li>

<%= link_to "Edit", edit_patient_path %>


<%= link_to "View your Appointment" , consultations_path %>

app/views/user_profiles/edit.html.erb
<h1>Edit.html.erb</h1>

app/views/user_profiles/new.html.erb
<h1>Fill the details</h1>
 <%= simple_form_for @profile do |f|%>
   <%= f.input :name%>
   <%= f.input :age%>
   <%= f.input :gender%>
   <%= f.input :bloodgroop%>
   <%= f.input :address%>
   <%= f.input :city%>
   <%=f.submit "Save and next"%>
 <% end %>